version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - healthcare-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - healthcare-db:/app/data
    networks:
      - healthcare-network
    environment:
      - DATABASE_URL=sqlite:///./data/healthcare.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  healthcare-db:

networks:
  healthcare-network:
    driver: bridge
