version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - healthcare-network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./healthcare.db:/app/healthcare.db
    networks:
      - healthcare-network
    environment:
      - DATABASE_URL=sqlite:///./healthcare.db
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

networks:
  healthcare-network:
    driver: bridge
