version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/healthcare.db:/app/backend/healthcare.db
    environment:
      - ALLOWED_ORIGINS=http://localhost:3000,https://your-cloudfront-distribution-id.cloudfront.net
      - PRODUCTION_FRONTEND_URL=https://your-cloudfront-distribution-id.cloudfront.net
    restart: unless-stopped
