@echo off
echo Starting Healthcare Center Backend...

echo Installing dependencies...
pip install -r requirements.txt

echo Initializing database...
python -c "from app.init_db import init_db; init_db()"

echo Starting server...
uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
